server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.6sr4x.mongodb.net/test?retryWrites=true&w=majority
      database: test

kafka:
  bootstrap-server: localhost:9092
  consumer:
    group-id: group_id
    auto-offset-reset: earliest


